# This workflow will do a clean installation of node dependencies
# build the source code and run tests across different versions of node and MongoDB

name: Node.js CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                mongodb-version: ["6.0"]

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.10.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}
                  mongodb-port: 27017

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test
              env:
                  TRAFIKVERKET_API_KEY: ${{ secrets.TRAFIKVERKET_API_KEY }}
