# This workflow will do a clean installation of node dependencies
# build the source code and run tests across different versions of node and MongoDB

name: Node.js CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
                mongodb-version: ["4.2", "4.4", "5.0", "6.0"]

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.10.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - name: Install dependencies
              run: npm ci

            - name: Compile typescript files
              run: npm run build

            - name: Run tests
              run: npm test
